name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      
      # This enables task distribution via Nx Cloud
      # Run this command as early as possible, before dependencies are installed
      # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
      # Uncomment this line to enable task distribution
      # - run: yarn nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"

      
      # Setup Node.js for frontend
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      # Setup .NET for backend
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      # Install frontend dependencies
      - run: yarn install --frozen-lockfile
      
      # Restore .NET dependencies for backend
      - run: yarn nx affected -t restore
      
      - uses: nrwl/nx-set-shas@v4

      # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
      # - run: yarn nx-cloud record -- echo Hello World
      
      # Run lint for frontend projects
      - run: yarn nx affected -t lint
      
      # Run tests for all affected projects  
      - run: yarn nx affected -t test
      
      # Build all affected projects
      - run: yarn nx affected -t build
